# -*- coding: utf-8 -*-
"""Retrieval-augmented-generation-with-generative-AI-elements for searching books.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T4u7rtFGms8qJDYlG4FDPPHiTLUUbsg6

#Simple generative AI model to discover a book
"""

# installing needed libraries for web requests, deep learning and transforming
!pip install transformers requests torch

# library needed for embeddings
!pip install sentence-transformers

# storing embeddings
!pip install faiss-cpu

# import needed libraries: request to get the ebook, optional is for code documentation
# SentenceTransformer to transfrom text to vector embeddings, numpy for delaing wiht numbers
# faiss help in finding relevant chunks in the book, pipelin is to use the flant5 model to create answers
import requests
from typing import Optional
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss
from transformers import pipeline

# saving the book in a variable
#print("book saved in variable")
url = "Link to ebook"
ebook_text = requests.get(url).text

# import regular expressions
import re
# making chunks by splitting text on any combination of newlines
chunks = re.split(r'\n\s*\n', ebook_text)
chunks = [chunk.strip() for chunk in chunks if len(chunk.strip()) > 50]
print(f"regex method: {len(chunks)} chunks")

# creating embeddings
#print("creating embeddings")
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = embedding_model.encode(chunks, show_progress_bar=True)

# create FAISS index for similarity search
#print("building search index")
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings).astype('float32'))

# use Flan-T5
# free generative model that creates natural responses
generator = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    max_length=512,
    truncation=True
)

# create generative chatbot function
def ask_about_book(question, top_k=3):
    """
    ask questions about the book and get AI-powered repsonses
    Args:
       question: your question about the book
       top_k: How many relevant passages to search (default 3)
    """
    # find most relevant parts
    question_embedding = embedding_model.encode([question])
    distances, indices = index.search(np.array(question_embedding).astype('float32'), top_k)
    # combine the relevant passages
    context = "\n\n".join([chunks[idx] for idx in indices[0]])
    # limit context length to not overwhelm the model
    if len(context) > 1000:
        context = context[:1000] + "..."
    # create a prompt for the model
    prompt = f"""based on the following passages from pride and prejudice, answer question in a conversational way.
context:{context}
Question: {question}
Answer:"""
    try:
        # Generate the answer!
        result = generator(prompt, max_length=200, min_length=20, do_sample=True, temperature=0.7)
        answer = result[0]['generated_text']
        print(f"\n AI generated answer:")
        print(f"{answer}")
        print(f"\n based on these passages and parts from the books:")
        print(context[:400] + "..." if len(context) > 400 else context)

        return answer
    except Exception as e:
        print(f"Error occurred: {e}")
        print(f"\n here are the relevant passages i found:")
        print(context[:800])
        return "Sorry, i encounterd an issue generating the response"

# test it
print("Generative AI ebook chatbot ready!")
print("-"*20)
print("This AI will generate natural responses based on the book content")

# example questions
questions = ["who is the writer?",
             "where was the book published?",
             "what is the hero first name?",
             "describe the book"]
for q in questions:
    print(f"\n question:{q}")
    ask_about_book(q)
    print("\n" + "-"*10)

# Interactive mode
print("\n\n" + "-"*10)
print("Interactive mode - ask questions")
print("-"*10)
print("Type your questions below (type 'quit to exit)\n")
while True:
    user_question = input("the question: ")
    if user_question.lower() in ['quit', 'exit', 'q']:
        print("\n thanks for the chat, goodbye.")
        break
    if user_question.strip():
        ask_about_book(user_question)
        print()